name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (backend)
        working-directory: ./backend
        run: npm ci
      - name: Run linter
        working-directory: ./backend
        run: npm run lint
      - name: Run tests (placeholder)
        working-directory: ./backend
        run: |
          echo "No tests defined yet"
